config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  get "reviews/:id", to: "reviews#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant_id, presence: true
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.save
    redirect_to restaurants_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class='navbar'>
      <%= link_to 'back to list', restaurants_path, { :class=>"navbar-item" }%>
      <%= link_to 'add a restaurant', new_restaurant_path, { :class=>"navbar-item" } %>
    </div>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class='banner-list'></div>
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offeset-3 ">
    <h1>Restaurants list</h1>
    <% @restaurants.each do |restaurant| %>
      <ul>
        <li>
          <%= restaurant.name %> -
          <%= restaurant.category %> -
          <%= link_to 'details', restaurant_path(restaurant) %> -
          <%= link_to new_restaurant_review_path(restaurant) do %>
          <i class="fa fa-commenting-o" aria-hidden="true"></i>
          <% end %>
        </li>
      </ul>
    <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h1>Add a restaurant</h1>
      <%= simple_form_for @restaurant do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
        <%= f.submit "add a restaurant", class: "btn btn-primary" %>
        <%= link_to 'back', restaurants_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="banner">
  <h1>
    <%= @restaurant.name %>
  </h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="box">
        <p>
          <strong>Category :</strong><%= @restaurant.category %>
        </p>
        <p>
          <strong>Address :</strong><%= @restaurant.address %>
        </p>
        <p>
          <strong>Phone :</strong><%= @restaurant.phone_number %>
        </p>
        <br>
        <p><strong>Reviews :</strong></p>
        <% @restaurant.reviews.each do |review| %>
          <ul>
            <li>
              <%= review.content %> -
              <% review.rating.times do %>
              <i class="fa fa-star" aria-hidden="true"></i>
              <% end %>
            </li>
          </ul>
        <% end %>
      </div>

      </div>
    </div>
  </div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.submit "add a review", class: "btn btn-primary" %>
      <% end %>
        <%= link_to 'back', restaurants_path %>
    </div>
  </div>
</div>